version: "3.3"

services:
  nextjs:
    ports:
      - 3002:3002
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /usr/src/app
      - /usr/src/app/.next
    env_file:
      - .env