version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - images:/usr/src/app/public/bilder
      - next:/usr/src/app/.next
    environment:
      - DATABASE_URL=mongodb://nollkit:nollkit@mongo:27017/db?authSource=admin&retryWrites=true&w=majority
      - PASSWORD=123
    
  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data/originalData:/data/db
      - ./data/mongo/conf:/etc/mongo
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: nollkit
    #   MONGO_INITDB_ROOT_PASSWORD: nollkit
    command: --replSet nollkitdb --bind_ip_all
    # entrypoint: [ "/usr/bin/mongod", "--replSet", "nollkitdb", "--bind_ip-all"]

  mongo.replicationData.one:
    container_name: "mongo.replicationData.one"
    image: mongo:4.4.18
    networks:
      - common.network
    ports:
      - 27018:27017
    depends_on:
      - mongo      
    volumes:
      - ./data/replicationData.one:/data/db
    restart: unless-stopped
    command: --replSet nollkitdb --bind_ip_all
    # entrypoint: [ "/usr/bin/mongod", "--replSet", "nollkitdb", "--bind_ip-all"]
  
  mongo.replicationData.two:
    container_name: "mongo.replicationData.two"
    image: mongo:4.4.18
    networks:
      - common.network
    ports:
      - 27019:27017
    depends_on:
      - mongo
    volumes:
      - ./data/replicationData.two:/data/db
    restart: unless-stopped
    command: --replSet nollkitdb --bind_ip_all
    # entrypoint: [ "/usr/bin/mongod", "--replSet", "nollkitdb", "--bind_ip-all"]

volumes:
  images:
  next:
  originalData:
    name: "originalData"
  replicationData.one:
    name: "replicationData.one"
  replicationData.two:
    name: "replicationData.two"

networks:
  default:
  common.network:
    driver: bridge
