version: "3.3"

services:
  mongo:
    image: mongo:4.4.18
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: nollkit
      MONGO_INITDB_ROOT_PASSWORD: nollkit
  nextjs:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - images:/usr/src/app/public/bilder
      - next:/usr/src/app/.next
    env_file:
      - .env
volumes:
  next:
  images:
networks:
  default:
